# SAM File
# Took the basis from https://github.com/awslabs/serverless-application-model/tree/master/examples/apps/hello-world-python3
# Then for API gateway: https://github.com/awslabs/serverless-application-model/tree/master/examples/apps/microservice-http-endpoint-python3

AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A starter AWS Lambda function.
Resources:
  helloworldpython3:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler # source file name.handler function name
      Runtime: python3.7
      CodeUri: src/ # Directory of source file
      Description: A starter AWS Lambda function.
      MemorySize: 128
      Timeout: 3
      Environment: # Setting envrionment variables TABLE_NAME and REGION_NAME
        Variables:
          TABLE_NAME: !Ref Table
          REGION_NAME: !Ref AWS::Region
      Events:  # Add API Gateway with the following APIs
        HelloWorldSAMAPI:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
      Policies: # Policy that allows to do CRUD operations on table Table
        - DynamoDBCrudPolicy:
            TableName: !Ref Table

  Table:  # Table in dynamodb
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: greeting
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
